GET http://localhost:3000/lectures HTTP/1.1

###
#GET http://localhost:3000/lectures/5cabe6021c9d44000025afb3 HTTP/1.1
GET http://localhost:3000/lectures/MWA HTTP/1.1

###

POST http://localhost:3000/lectures HTTP/1.1
Content-Type: application/json

{
    "data":{
        "course":"XYZ",
        "lecture":"lecture zzz"
    }
}

###
POST http://localhost:3000/grades HTTP/1.1
?name='edwin Bernal'
content-type: application/json